apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-label
  template:
    metadata:
      labels:
        app: hello-label
    spec:
      containers:
      - name: hello-container
        image: keitaronishijima/hello:latest
        ports:
        - containerPort: 5000